/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GdDownloadData {
    }
}
declare global {
    interface HTMLGdDownloadDataElement extends Components.GdDownloadData, HTMLStencilElement {
    }
    var HTMLGdDownloadDataElement: {
        prototype: HTMLGdDownloadDataElement;
        new (): HTMLGdDownloadDataElement;
    };
    interface HTMLElementTagNameMap {
        "gd-download-data": HTMLGdDownloadDataElement;
    }
}
declare namespace LocalJSX {
    interface GdDownloadData {
    }
    interface IntrinsicElements {
        "gd-download-data": GdDownloadData;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gd-download-data": LocalJSX.GdDownloadData & JSXBase.HTMLAttributes<HTMLGdDownloadDataElement>;
        }
    }
}
